### PR TITLE
update import paths to new repository location

### PR DESCRIPTION
**Pull request by mb0**

### CODE REVIEW

**Comment by mattn** [comment]
ping @dgryski @rsc

**Comment by dgryski** [comment]
LGTM.  I do not have a commit bit on this repository though, so it's up to @rsc to merge I guess.

**Comment by Rolinh** [comment]
Why does it take so long to merge this simple pull request? Being unable to `go get github.com/google/codesearch/...` is pretty annoying for someone willing to use codesearch.

**Comment by mb0** [comment]
i guess the code was auto-migrated from code.google.com and nobody responsible is receiving the pr notification.

**Comment by mattn** [comment]
But I did ping at https://github.com/google/codesearch/pull/39#issuecomment-93215841
He might not read notification from github. Or he may have opinion about contribution on github.

**Comment by rsc** [comment]
I rewrote the import paths. Long term we are probably going to use Gerrit for changes, but I haven't set it up yet.

**Comment by mb0** [comment]
there are still references to code.google.com in the code

https://github.com/google/codesearch/blob/master/cmd/csearch/csearch.go#L15

and in the readme and build scripts:

https://github.com/google/codesearch/blob/master/README#L5
https://github.com/google/codesearch/blob/master/README#L12
https://github.com/google/codesearch/blob/master/lib/buildall#L17
https://github.com/google/codesearch/blob/master/lib/README.template#L2

**Comment by tv42** [comment]
Ping. This was not fixed.

**Pull request closed without merging**
