### PR TITLE
index: fix bug in siftUp

### LINKED ISSUE #35: fix bug in siftUp()
```
siftUp is wrong if heap size > 3
```

Original issue reported on code.google.com by `kelvinlau0107@gmail.com` on 16 Nov 2013 at 3:45

Attachments:
- [write.go.patch](https://storage.googleapis.com/google-code-attachments/codesearch/issue-35/comment-0/write.go.patch)

### PR DESCRIPTION
**Pull request by dgryski**
Fixes #35

### CODE REVIEW

**Comment by dgryski** [comment]
This is just taking the attached patches from #35 and making a github pull request.

I agree there is a bug in siftUp(), but I'm not entirely sure why it doesn't manifest itself in production.

**Comment by pombredanne** [comment]
Any reason why this is not merged in master?

**Comment by dgryski** [comment]
Mostly because @rsc is busy with other things.

**Comment by dgryski** [comment]
I just hit this with my current corpus.  I had added a `panic()` to `mergePost()` in case I ever tried to merge out-of-order elements and for the first time today it fired.  So, indeed this does happen in production, but clearly it is rare.

Pinging @rsc again to get this merged.

**Comment by pombredanne** [comment]
@dgryski may be Russ has lost interest in this codebase or has not the time to handle this at all?
I can see that @dominikh and especially @junkblocker have reasonably active forks. May it would be time to take over the code and maintain it entirely elsewhere?
Just food for subversive thoughts

**Comment by dgryski** [comment]
And both forks have included the `siftUp()` patch too.  I agree the README should probably be updated to point to the other maintained forks.

**Pull request merged**
